const $ = (selector) => document.querySelector(selector);
const state = { language: localStorage.getItem("releaseguard-language") || "zh" };
const copy = {
  zh: { eyebrow:"发布前检查", title:"在用户发现问题之前，先把 Release 检查做好。", lede:"粘贴一个 GitHub Release。ReleaseGuard 会在几秒内检查安装包、校验和、平台覆盖、版本命名与二进制头。", targetLabel:"GitHub 仓库或 Release 地址", check:"检查 Release", hint:"公开仓库无需 Token。检查在本页与 GitHub 之间完成，不上传你的项目。", emptyTitle:"一次粘贴，得到发布健康报告。", emptyCopy:"从上方输入公开仓库开始，报告会明确告诉你发布前要修什么。", loading:"正在检查 Release 资产…", footer:"开源 · Vercel 部署 · 无需登录", score:"分数", pass:"通过", warning:"警告", error:"错误", coverage:"平台覆盖", assets:"可下载文件", findings:"检查结果", download:"下载", recommended:"适合当前设备", noAsset:"没有可下载文件", openRelease:"打开 Release", passed:"通过", failed:"失败" },
  en: { eyebrow:"SHIP WITH CONFIDENCE", title:"Release quality, before your users find the bug.", lede:"Paste a GitHub release. ReleaseGuard checks assets, checksums, platform coverage, version names, and binary headers in seconds.", targetLabel:"GitHub repository or release URL", check:"Check release", hint:"Public repositories work without a token. Checks run between this page and GitHub; your project is not uploaded.", emptyTitle:"A release health check in one paste.", emptyCopy:"Start with a public repository above. The report will show exactly what to fix before shipping.", loading:"Inspecting release assets…", footer:"Open source · runs on Vercel · no sign-in", score:"Score", pass:"Pass", warning:"Warning", error:"Error", coverage:"Platform coverage", assets:"Downloadable assets", findings:"Findings", download:"Download", recommended:"Best match for this device", noAsset:"No downloadable assets", openRelease:"Open release", passed:"Pass", failed:"Fail" }
};
const t = (key) => copy[state.language][key] || key;
function applyLanguage() { document.documentElement.lang = state.language === "zh" ? "zh-CN" : "en"; document.querySelectorAll("[data-i18n]").forEach((el) => { el.textContent = t(el.dataset.i18n); }); $("#target").placeholder = state.language === "zh" ? "owner/repo 或 https://github.com/owner/repo/releases/tag/v1.2.3" : "owner/repo or https://github.com/owner/repo/releases/tag/v1.2.3"; $("#language").textContent = state.language === "zh" ? "中文 / EN" : "EN / 中文"; }
function bytes(value) { if (!value) return "0 B"; const units=["B","KB","MB","GB"]; let i=0,n=value; while(n>=1024&&i<units.length-1){n/=1024;i++;} return `${n.toFixed(n>=10||i===0?0:1)} ${units[i]}`; }
function platformLabel(platform) { return state.language === "zh" ? ({macos:"macOS",windows:"Windows",linux:"Linux",android:"Android",other:"其他"}[platform] || platform) : platform; }
function assetLabel(item) { return `${platformLabel(item.platform)} · ${item.declaredArch === "unknown" ? "" : item.declaredArch}`.replace(/ · $/, ""); }
function recommendedAsset(assets) { const ua = navigator.userAgent.toLowerCase(); const platform = ua.includes("mac") ? "macos" : ua.includes("win") ? "windows" : ua.includes("linux") ? "linux" : null; if (!platform) return assets[0]; return assets.find((x) => x.platform === platform && (x.declaredArch === "universal" || (platform === "macos" ? ua.includes("arm") ? x.declaredArch === "arm64" : x.declaredArch === "x64" : true))) || assets.find((x) => x.platform === platform) || assets[0]; }
function render(report) {
  const color = report.conclusion === "pass" ? "#237a4b" : report.conclusion === "warning" ? "#a26400" : "#a63737";
  const recommend = recommendedAsset(report.assets);
  const findings = report.findings.slice(0, 14).map((f) => `<li><span>${escapeHtml(f.message)}${f.asset ? `<small class="asset-meta">${escapeHtml(f.asset)}</small>` : ""}</span><span class="badge ${f.level}">${t(f.level)}</span></li>`).join("");
  const assets = report.assets.map((item) => `<li class="asset"><div class="asset-info"><div class="asset-name" title="${escapeHtml(item.asset.name)}">${escapeHtml(item.asset.name)}</div><div class="asset-meta">${assetLabel(item)} · ${bytes(item.asset.size)} · ${item.asset.downloadCount || 0} downloads</div></div><a class="download" href="${escapeHtml(item.asset.url)}" target="_blank" rel="noreferrer" download>${t("download")}</a></li>`).join("");
  const apiRecommendation = report.recommendation?.asset ? report.recommendation : null;
  $("#report").innerHTML = `<div class="report-head"><div><h2>${escapeHtml(report.release.name || report.release.tag)}</h2><div class="repo-meta">${escapeHtml(report.release.repository)} · ${escapeHtml(report.release.tag)}${report.release.publishedAt ? ` · ${new Date(report.release.publishedAt).toLocaleDateString()}` : ""}</div><a href="${escapeHtml(report.release.url)}" target="_blank" rel="noreferrer">${t("openRelease")} ↗</a></div><div class="score" style="--score:${report.score};--score-color:${color}"><span>${report.score}<small>${t("score")}</small></span></div></div>${apiRecommendation ? `<div class="recommend"><span>↓</span><strong>${t("recommended")}<br><small>${escapeHtml(apiRecommendation.asset.name)}</small></strong><em>${escapeHtml(apiRecommendation.reason)}</em><a href="${escapeHtml(apiRecommendation.asset.url)}" target="_blank" rel="noreferrer" download>${t("download")}</a></div>` : ""}<div class="summary"><div class="stat pass"><b>${report.summary.pass}</b><span>${t("pass")}</span></div><div class="stat warning"><b>${report.summary.warning}</b><span>${t("warning")}</span></div><div class="stat error"><b>${report.summary.error}</b><span>${t("error")}</span></div></div><div class="report-grid"><div class="panel"><h3>${t("findings")}</h3><ul>${findings || `<li>${t("passed")}</li>`}</ul></div><div class="panel"><h3>${t("assets")}</h3><ul>${assets || `<li>${t("noAsset")}</li>`}</ul></div></div>`;
  $("#report").hidden = false;
}
function escapeHtml(value) { return String(value).replace(/[&<>"']/g, (c) => ({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c])); }
$("#language").addEventListener("click", () => { state.language = state.language === "zh" ? "en" : "zh"; localStorage.setItem("releaseguard-language", state.language); applyLanguage(); });
$("#check-form").addEventListener("submit", async (event) => { event.preventDefault(); const target = $("#target").value.trim(); if (!target) return; $("#empty").hidden = true; $("#error").hidden = true; $("#report").hidden = true; $("#loading").hidden = false; $("#check").disabled = true; try { const response = await fetch(`/api/check?target=${encodeURIComponent(target)}`); const payload = await response.json(); if (!response.ok) throw new Error(payload.error || "Request failed"); render(payload); } catch (error) { $("#error").textContent = error.message; $("#error").hidden = false; } finally { $("#loading").hidden = true; $("#check").disabled = false; } });
applyLanguage();
